Fix typings path
The typings file name is wrongly pointing to `./lib/index.ts` (which does not exists) creating a tsc compilation error

```error TS7016: Could not find a declaration file for module '@tsed/swagger'. '/Users/javiergomez/workspace/node/tsed/test/node_modules/@tsed/swagger/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/tsed__swagger` if it exists or add a new declaration (.d.ts) file containing `declare module '@tsed/swagger';`

3 import {Description, Example} from "@tsed/swagger";```